"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowLeft, BadgeCheck, Bell, BellRing, Check, CheckCheck, CheckCircle2, ChevronLeft, CircleX, Clock3, Eye, EyeOff, FileClock, FileSpreadsheet, Grid2X2, LoaderCircle, LockKeyhole, LogOut, MapPin, Megaphone, Menu, MessageCircle, Pencil, Phone, Plus, RotateCw, Search, Settings2, ShieldCheck, Star, Trash2, UserRound, UsersRound, X } from "lucide-react";
import { getCategory, normalizeSearch, whatsappUrl, type AdminDirectory, type CategoryRecord, type NotificationRecord } from "@/lib/catalog";
import { CategoryIcon, Logo, Modal } from "@/components/ui";
import ManagementEditor, { type EditorState, type EntityKind } from "@/components/management-editor";
import CampaignManagement from "@/components/campaign-management";
import SettingsEditor from "@/components/settings-editor";
import AdminImport from "@/components/admin-import";

type Tab = "requests" | "directory" | "categories" | "addresses" | "advertisements" | "members" | "notifications" | "settings" | "import";
const tabs: Array<{ id: Tab; name: string; icon: typeof FileClock }> = [{ id: "requests", name: "طلبات المهن", icon: FileClock }, { id: "directory", name: "الدليل المنشور", icon: UsersRound }, { id: "import", name: "استيراد Excel", icon: FileSpreadsheet }, { id: "categories", name: "التصنيفات والتخصصات", icon: Grid2X2 }, { id: "addresses", name: "عناوين جنزور", icon: MapPin }, { id: "advertisements", name: "إدارة الإعلانات", icon: Megaphone }, { id: "members", name: "أعضاء الموقع", icon: UserRound }, { id: "notifications", name: "الإشعارات", icon: Bell }, { id: "settings", name: "إعدادات الموقع", icon: Settings2 }];
const statusLabels: Record<string, string> = { pending: "قيد المراجعة", approved: "منشور", rejected: "مرفوض / موقوف" };
type Confirmation = { id: string; kind: EntityKind; action: "delete" | "approve"; label: string; price?: number };

export default function AdminPanel({ initialData, initialTab, username = "admin", role = "admin" }: { initialData: AdminDirectory; initialTab?: string; username?: string; role?: "admin" | "moderator" }) {
  const isModerator = role === "moderator";
  const visibleTabs = isModerator ? tabs.filter((item) => ["requests", "directory", "categories", "advertisements", "notifications"].includes(item.id)) : tabs;
  const starting = visibleTabs.some((tab) => tab.id === initialTab) ? initialTab as Tab : "requests";
  const [data, setData] = useState(initialData), [tab, setTab] = useState<Tab>(starting), [search, setSearch] = useState("");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [status, setStatus] = useState(starting === "requests" ? "pending" : "all"), [rootFilter, setRootFilter] = useState("");
  const [busy, setBusy] = useState<string | null>(null), [editing, setEditing] = useState<EditorState | null>(null), [confirmation, setConfirmation] = useState<Confirmation | null>(null);
  const [toast, setToast] = useState<{ text: string; error: boolean } | null>(null), [permission, setPermission] = useState<NotificationPermission | "unsupported">("default");
  const [notificationSelectionMode, setNotificationSelectionMode] = useState(false), [selectedNotificationIds, setSelectedNotificationIds] = useState<Set<string>>(new Set());
  const [bulkDeleteConfirmation, setBulkDeleteConfirmation] = useState<{ ids: string[]; deleteAll: boolean } | null>(null);
  const knownNotifications = useRef(new Set(initialData.notifications.map((notification) => notification.id)));
  const closeEditor = () => setEditing(null), closeConfirmation = () => setConfirmation(null);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Read the browser notification permission on mount.
  useEffect(() => { setPermission(typeof Notification === "undefined" ? "unsupported" : Notification.permission); }, []);
  useEffect(() => {
    if (busy) return;
    let cancelled = false;
    const synchronize = async () => {
      if (document.hidden) return;
      try {
        const response = await fetch("/api/admin", { cache: "no-store" });
        if (cancelled) return;
        if (response.status === 401 || response.status === 403) { window.location.assign(response.status === 401 ? "/login" : "/account"); return; }
        if (!response.ok) return;
        const next: AdminDirectory = await response.json();
        const fresh = next.notifications.filter((item) => !item.read && !knownNotifications.current.has(item.id));
        knownNotifications.current = new Set(next.notifications.map((item) => item.id));
        setData(next);
        const serviceNotice = fresh.find((item) => item.type === "service") ?? fresh[0];
        if (serviceNotice) {
          setToast({ text: `${serviceNotice.title}: ${serviceNotice.message}`, error: false });
          if (typeof Notification !== "undefined" && Notification.permission === "granted") new Notification(serviceNotice.title, { body: serviceNotice.message, icon: "/images/logo-janzour.png", tag: serviceNotice.id });
        }
      } catch { /* Retry after temporary connection errors without losing the dashboard. */ }
    };
    const timer = setInterval(synchronize, 10000); window.addEventListener("focus", synchronize);
    return () => { cancelled = true; clearInterval(timer); window.removeEventListener("focus", synchronize); };
  }, [busy]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 7000); return () => clearTimeout(timer); }, [toast]);

  const roots = data.categories.filter((category) => !category.parentId);
  const pending = data.services.filter((service) => service.status === "pending").length, published = data.services.filter((service) => service.status === "approved").length;
  const pendingAds = data.ads.filter((ad) => ad.status === "pending").length, unread = data.notificationUnread;
  const title = visibleTabs.find((item) => item.id === tab)?.name ?? "لوحة التحكم";
  const filteredServices = data.services.filter((service) => (tab === "directory" ? service.status === "approved" : service.status !== "approved") && (status === "all" || service.status === status) && (!rootFilter || getCategory(service.category, data.categories).parentId === rootFilter) && normalizeSearch(`${service.name} ${service.phone} ${service.phoneSecondary} ${service.area} ${getCategory(service.category, data.categories).name}`).includes(normalizeSearch(search)));
  const filteredAds = data.ads.filter((ad) => (status === "all" || ad.status === status) && normalizeSearch(`${ad.businessName} ${ad.text} ${ad.phone}`).includes(normalizeSearch(search)));
  const filteredMembers = data.members.filter((member) => normalizeSearch(`${member.name} ${member.username} ${member.phone}`).includes(normalizeSearch(search)));
  const filteredRoots = roots.filter((category) => (!rootFilter || category.id === rootFilter) && (!search || normalizeSearch(`${category.name} ${data.categories.filter((item) => item.parentId === category.id).map((item) => item.name).join(" ")}`).includes(normalizeSearch(search))));
  const allNotificationsSelected = data.notifications.length > 0 && data.notifications.every((notification) => selectedNotificationIds.has(notification.id));
  function selectTab(value: Tab) { setTab(value); setMobileMenuOpen(false); setSearch(""); setRootFilter(""); setStatus(value === "requests" ? "pending" : "all"); setNotificationSelectionMode(false); setSelectedNotificationIds(new Set()); setBulkDeleteConfirmation(null); }
  async function mutate(method: "GET" | "POST" | "PATCH" | "DELETE", body?: Record<string, unknown>, success = "تم الحفظ بنجاح.") {
    const key = typeof body?.id === "string" ? body.id : method === "GET" ? "refresh" : "saving"; setBusy(key);
    try {
      const response = await fetch("/api/admin", { method, cache: "no-store", headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
      const result = await response.json();
      if (response.status === 401 || response.status === 403) { window.location.assign(response.status === 401 ? "/login" : "/account"); throw new Error("لم تعد هذه الجلسة تملك صلاحية لوحة الإدارة."); }
      if (!response.ok) throw new Error(result.error ?? "تعذر تنفيذ الطلب.");
      setData(result); knownNotifications.current = new Set(result.notifications.map((item: NotificationRecord) => item.id));
      setToast({ text: success, error: false }); return true;
    } catch (error) { setToast({ text: error instanceof Error ? error.message : "تعذر الاتصال.", error: true }); return false; }
    finally { setBusy(null); }
  }
  async function change(id: string, kind: EntityKind, action: string) {
    const ok = await mutate("PATCH", { id, type: kind, action }, action === "approve" ? kind === "ad" ? "تم تأكيد الدفع وتفعيل الإعلان." : "تمت الموافقة، والخدمة ظهرت في الدليل." : action === "feature" ? "تم تحديث تمييز الخدمة." : "تم إيقاف النشر وتحديث الطلب.");
    if (ok) setConfirmation(null);
  }
  async function saveEditor(values: Record<string, unknown>) {
    if (!editing) return false;
    const ok = await mutate(editing.item ? "PATCH" : "POST", { type: editing.kind, action: "edit", id: editing.item?.id, values }, editing.item ? "تم حفظ التعديلات." : "تمت الإضافة بنجاح.");
    if (ok) setEditing(null); return ok;
  }
  async function toggleCategory(category: CategoryRecord) { await mutate("PATCH", { type: "category", id: category.id, action: "edit", values: { ...category, active: !category.active } }, category.active ? "تم إخفاء التصنيف وخدماته دون حذفها." : "تم إظهار التصنيف."); }
  async function logout() { setBusy("logout"); try { const response = await fetch("/api/auth", { method: "DELETE" }); if (!response.ok) throw new Error(); window.location.assign("/"); } catch { setBusy(null); setToast({ text: "تعذر الخروج. حاول مرة أخرى.", error: true }); } }
  async function enableNotifications() { try { if (typeof Notification === "undefined") return; const value = await Notification.requestPermission(); setPermission(value); setToast({ text: value === "granted" ? "تم تفعيل تنبيهات المتصفح أثناء فتح لوحة التحكم." : "تنبيهات اللوحة تظل شغالة حتى بدون إذن المتصفح.", error: false }); } catch { setToast({ text: "المتصفح لا يدعم التنبيهات هنا. إشعارات اللوحة تظل متاحة.", error: true }); } }
  async function openNotification(notification: NotificationRecord) {
    const destination = notification.type === "service" ? "requests" : notification.type === "ad" ? "advertisements" : "members";
    if (!notification.read) await mutate("PATCH", { type: "notification", id: notification.id, action: "read" }, "تم تحديد الإشعار كمقروء.");
    selectTab(destination);
    const label = notification.type === "service" ? data.services.find((item) => item.id === notification.entityId)?.name : notification.type === "ad" ? data.ads.find((item) => item.id === notification.entityId)?.businessName : data.members.find((item) => item.id === notification.entityId)?.name;
    setSearch(label ?? ""); if (destination === "requests") setStatus("all");
  }
  function toggleNotificationSelection(id: string) {
    setSelectedNotificationIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  }
  function toggleAllNotifications() {
    setSelectedNotificationIds(allNotificationsSelected ? new Set() : new Set(data.notifications.map((notification) => notification.id)));
  }
  async function deleteBulkNotifications() {
    if (!bulkDeleteConfirmation) return;
    const { ids, deleteAll } = bulkDeleteConfirmation;
    const ok = await mutate("DELETE", { type: "notification", action: deleteAll ? "delete-all" : "delete-selected", ...(deleteAll ? {} : { ids }) }, deleteAll ? "تم حذف كل الإشعارات." : `تم حذف ${ids.length} إشعار.`);
    if (ok) { setSelectedNotificationIds(new Set()); setNotificationSelectionMode(false); setBulkDeleteConfirmation(null); }
  }
  const descriptions: Record<Tab, string> = { requests: "المهن الجديدة بتوصلك هنا، ومعاها إشعار، قبل ما تظهر لأي زائر.", directory: isModerator ? "استعرض الخدمات المنشورة وبياناتها." : "عدّل بيانات أي مقدم خدمة، وميّز الخدمات أو أوقف نشرها.", categories: "الأقسام الرئيسية والتخصصات بداخلها. أضف، عدّل، أخفِ أو احذف.", addresses: "عناوين جنزور، مع اختيار عنوان آخر وخانة كتابة تلقائية للزائر.", advertisements: isModerator ? "راجع إعلانات العملاء ووافق عليها أو أوقفها." : "إعلانات العملاء وإعدادات الشريط المتحرك وألوانه.", members: "الأعضاء المسجلون بالموقع فقط. العضوية لا تضيف الشخص إلى المهنيين.", notifications: isModerator ? "إشعارات طلبات المهن والإعلانات المتاحة لصلاحيتك." : "طلبات المهن والإعلانات والأعضاء الجدد.. محفوظة لحين قراءتها.", settings: "اسم الموقع ونصوصه ورقم التواصل وإعدادات المساحة الإعلانية.", import: "ارفع ملف Excel، راجع الأسماء والأرقام والتكرارات، ثم أضف المعامل كطلبات بانتظار الموافقة.", };
  const editorTitle = editing ? `${editing.item ? "تعديل" : "إضافة"} ${editing.kind === "service" ? "مقدم خدمة" : editing.kind === "ad" ? "إعلان" : editing.kind === "category" ? "تصنيف أو تخصص" : editing.kind === "area" ? "عنوان" : "عضو"}` : "";
  const count = tab === "requests" || tab === "directory" ? filteredServices.length : tab === "advertisements" ? filteredAds.length : tab === "members" ? filteredMembers.length : tab === "notifications" ? unread : undefined;

  return <div className={`admin-shell ${isModerator ? "admin-shell-moderator" : ""}`}><aside className={`admin-sidebar ${mobileMenuOpen ? "admin-sidebar-open" : ""}`}><Logo footer name={data.settings.siteName}/><div className="admin-sidebar-label">{isModerator ? "إشراف دليل قرية جنزور" : "إدارة دليل قرية جنزور"}</div><button type="button" className="admin-mobile-menu-toggle" aria-expanded={mobileMenuOpen} aria-controls="admin-section-navigation" onClick={() => setMobileMenuOpen((open) => !open)}>{mobileMenuOpen ? <X size={18}/> : <Menu size={18}/>}<span>أقسام الإدارة</span><ChevronLeft size={15}/></button><nav id="admin-section-navigation" aria-label="أقسام لوحة الإدارة">{visibleTabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => selectTab(item.id)}><item.icon size={20}/>{item.name}{item.id === "requests" && pending > 0 ? <span>{pending}</span> : item.id === "notifications" && unread > 0 ? <span>{unread}</span> : item.id === "members" ? <span>{data.memberCount}</span> : item.id === "advertisements" && pendingAds > 0 ? <span>{pendingAds}</span> : null}</button>)}</nav><div className="admin-sidebar-bottom"><a href="/" target="_blank" rel="noopener noreferrer"><Grid2X2 size={18}/>عرض الموقع<ArrowLeft size={16}/></a><a href={whatsappUrl(data.settings.phone)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>واتساب مكتب الجمال</a><button onClick={logout} disabled={busy === "logout"}><LogOut size={18}/>تسجيل الخروج</button></div></aside><main className="admin-main"><header className="admin-topbar"><div><span className="admin-breadcrumb">دليل جنزور <ChevronLeft size={13}/>لوحة الإدارة</span><h1>{isModerator ? `أهلًا بيك، يا مشرف الدليل` : "أهلً�� بيك، يا مدير الدليل"}</h1><p>{isModerator ? "راجع طلبات المهن والإعلانات، وأدر التصنيفات والإشعارات المخصصة لك." : "كل تفاصيل الموقع في إيدك.. وكل طلب جديد بيوصلك الأول"}</p></div><div className="admin-topbar-actions"><button className="admin-notification-button" onClick={() => selectTab("notifications")} aria-label="فتح إشعارات الإدارة"><BellRing size={21}/>{unread > 0 && <span className="bell-count">{unread}</span>}</button><div className="admin-user"><span><UserRound size={23}/></span><div><strong>{username}</strong><small>{isModerator ? "مشرف بصلاحيات محدودة" : "مدير الموقع"}</small></div></div></div></header>
    <div className="admin-stats"><button className="admin-stat" onClick={() => selectTab("requests")}><span className="stat-icon stat-orange"><FileClock size={24}/></span><div><span>مهن بانتظار المراجعة</span><strong>{pending}</strong><small>راجعها قبل النشر</small></div></button><button className="admin-stat" onClick={() => selectTab("directory")}><span className="stat-icon stat-green"><BadgeCheck size={24}/></span><div><span>مهن منشورة في الدليل</span><strong>{published}</strong><small>ظاهرة في تخصصاتها</small></div></button>{!isModerator && <button className="admin-stat" onClick={() => selectTab("members")}><span className="stat-icon stat-blue"><UsersRound size={24}/></span><div><span>عدد أعضاء الموقع</span><strong>{data.memberCount}</strong><small>عضويات مستقلة عن المهن</small></div></button>}<button className="admin-stat" onClick={() => selectTab("advertisements")}><span className="stat-icon stat-purple"><Megaphone size={24}/></span><div><span>إعلانات بانتظارك</span><strong>{pendingAds}</strong><small>مراجعة وتأكيد دفع</small></div></button></div>
    <div className="admin-review-notice"><ShieldCheck size={23}/><p><strong>{isModerator ? "لوحة المشرف بصلاحيات محددة." : "صلاحيات الأدمن الكاملة."}</strong> {isModerator ? "يمكنك مراجعة طلبات المهن والإعلانات وإدارة التصنيفات والإشعارات، بينما إعدادات الموقع وإدارة الأعضاء متاحة للأدمن فقط." : "التسجيل العادي عضوية فقط، وكل طلب مهنة جديد يظهر هنا مع إشعار."}</p>{unread > 0 && <button onClick={() => selectTab("notifications")}>{unread} إشعار جديد<ChevronLeft size={14}/></button>}</div>
    <section className="admin-content"><div className="admin-content-heading"><div><h2>{title}{count !== undefined && <span>{count}</span>}</h2><p>{descriptions[tab]}</p></div><div className="admin-heading-actions"><button className="button button-soft refresh-button" onClick={() => mutate("GET", undefined, "تم تحديث الطلبات والبيانات.")} disabled={busy === "refresh"}><RotateCw size={17} className={busy === "refresh" ? "spin" : ""}/>تحديث</button>{(tab === "requests" || tab === "directory") && !isModerator && <button className="button button-primary button-small" onClick={() => setEditing({ kind: "service" })}><Plus size={16}/>إضافة مهنة</button>}{tab === "categories" && <button className="button button-primary button-small" onClick={() => setEditing({ kind: "category" })}><Plus size={16}/>تصنيف جديد</button>}{tab === "addresses" && <button className="button button-primary button-small" onClick={() => setEditing({ kind: "area" })}><Plus size={16}/>عنوان جديد</button>}{tab === "advertisements" && !isModerator && <button className="button button-primary button-small" onClick={() => setEditing({ kind: "ad" })}><Plus size={16}/>إضافة إعلان</button>}</div></div>
    {["requests", "directory", "advertisements", "members", "categories"].includes(tab) && <div className="admin-toolbar"><div className="admin-search"><Search size={19}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث بالاسم أو الهاتف أو التخصص..." aria-label="البحث في بيانات الإدارة"/></div>{["requests", "advertisements"].includes(tab) && <select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="حالة الطلب"><option value="all">كل الحالات</option><option value="pending">قيد المراجعة</option>{tab === "advertisements" && <option value="approved">منشور</option>}<option value="rejected">مرفوض / موقوف</option></select>}{["requests", "directory", "categories"].includes(tab) && <select value={rootFilter} onChange={(event) => setRootFilter(event.target.value)} aria-label="التصنيف الرئيسي"><option value="">كل الأقسام</option>{roots.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select>}</div>}
    {(tab === "requests" || tab === "directory") && <div className="admin-service-list">{filteredServices.map((service) => <article className="admin-service-row" key={service.id}><div className="admin-service-summary"><span className="admin-category-icon" style={{ color: getCategory(service.category, data.categories).color, background: getCategory(service.category, data.categories).light }}><CategoryIcon icon={getCategory(service.category, data.categories).icon} size={26}/></span><div className="admin-service-name"><div><h3>{service.name}</h3><span className={`status-badge status-${service.status}`}>{statusLabels[service.status]}</span>{service.featured && <span className="admin-featured-badge"><Star size={12} fill="currentColor"/>مميز</span>}{service.demo && <span className="admin-demo-badge">نموذج توضيحي</span>}</div><p><span>{getCategory(service.category, data.categories).name}</span><span><MapPin size={12}/>{service.address || service.area}</span><a href={`tel:${service.phone}`} dir="ltr"><Phone size={12}/>{service.phone}</a></p></div><span className="admin-date">{new Date(service.createdAt).toLocaleDateString("ar-EG")}</span></div><p className="admin-service-description">{service.description}</p><div className="admin-row-actions"><button className="button button-soft button-small" onClick={() => setEditing({ kind: "service", item: service })}><Pencil size={15}/>تعديل البيانات</button><div>{service.status !== "approved" ? <><button className="button button-success button-small" disabled={busy === service.id} onClick={() => change(service.id, "service", "approve")}><Check size={15}/>موافقة ونشر</button>{service.status === "pending" && <button className="button button-danger-soft button-small" disabled={busy === service.id} onClick={() => change(service.id, "service", "reject")}><X size={15}/>رفض</button>}</> : <><button className={`button button-small ${service.featured ? "button-amber" : "button-soft"}`} disabled={busy === service.id} onClick={() => change(service.id, "service", "feature")}><Star size={15}/>{service.featured ? "إلغاء التمييز" : "تمييز"}</button><button className="button button-danger-soft button-small" disabled={busy === service.id} onClick={() => change(service.id, "service", "reject")}><EyeOff size={15}/>إيقاف النشر</button></>}<button className="icon-button admin-delete" disabled={busy === service.id} onClick={() => setConfirmation({ id: service.id, kind: "service", action: "delete", label: service.name })} aria-label={`حذف ${service.name}`}><Trash2 size={16}/></button></div></div></article>)}{!filteredServices.length && <AdminEmpty title={search ? "مفيش نتائج للبحث" : "كل الطلبات تحت السيطرة!"} text="أي مهنة جديدة هتوصلك هنا للمراجعة، ومعاها إشعار. مفيش نشر تلقائي."/>}</div>}
    {tab === "categories" && <div className="categories-management">{filteredRoots.map((category) => <div className="category-management-group" key={category.id}><div className="category-management-heading"><span className="admin-category-icon" style={{ background: category.light, color: category.color }}><CategoryIcon icon={category.icon} size={25}/></span><div><h3>{category.name}<span className={`status-badge ${category.active ? "status-approved" : "status-rejected"}`}>{category.active ? "ظاهر" : "مخفي"}</span></h3><p>{category.description}</p></div><div className="category-management-actions"><button className="button button-soft button-small" onClick={() => setEditing({ kind: "category", parentId: category.id })}><Plus size={14}/>تخصص</button><button className="icon-button" onClick={() => setEditing({ kind: "category", item: category })} aria-label={`تعديل ${category.name}`}><Pencil size={16}/></button><button className="icon-button" onClick={() => toggleCategory(category)} aria-label={`${category.active ? "إخفاء" : "إظهار"} ${category.name}`}>{category.active ? <EyeOff size={16}/> : <Eye size={16}/>}</button><button className="icon-button admin-delete" onClick={() => setConfirmation({ id: category.id, kind: "category", action: "delete", label: category.name })} aria-label={`حذف ${category.name}`}><Trash2 size={16}/></button></div></div><div className="specialties-management-list">{data.categories.filter((item) => item.parentId === category.id && (!search || normalizeSearch(item.name).includes(normalizeSearch(search)) || normalizeSearch(category.name).includes(normalizeSearch(search)))).map((item) => <div className="category-management-row" key={item.id}><CategoryIcon icon={item.icon} size={18}/><div><strong>{item.name}</strong><span>{data.services.filter((service) => service.category === item.id).length} مهنة مرتبطة</span></div><span className={`status-badge ${item.active ? "status-approved" : "status-rejected"}`}>{item.active ? "ظاهر" : "مخفي"}</span><div className="category-management-actions"><button className="icon-button" onClick={() => setEditing({ kind: "category", item })} aria-label={`تعديل ${item.name}`}><Pencil size={15}/></button><button className="icon-button" onClick={() => toggleCategory(item)} aria-label={`${item.active ? "إخفاء" : "إظهار"} ${item.name}`}>{item.active ? <EyeOff size={15}/> : <Eye size={15}/>}</button><button className="icon-button admin-delete" onClick={() => setConfirmation({ id: item.id, kind: "category", action: "delete", label: item.name })} aria-label={`حذف ${item.name}`}><Trash2 size={15}/></button></div></div>)}</div></div>)}{!filteredRoots.length && <AdminEmpty title="مفيش تصنيفات مطابقة" text="أضف تصنيفًا رئيسيًا جديدًا، ثم أضف التخصصات بداخله."/>}</div>}
    {tab === "addresses" && <div className="address-management-list">{data.areas.map((area) => <div className="address-management-row" key={area.id}><span><MapPin size={22}/></span><div><h3>{area.name}</h3><p>{data.services.filter((service) => service.area === area.name).length} خدمة مرتبطة • الترتيب {area.sortOrder}</p></div><button className="button button-soft button-small" onClick={() => setEditing({ kind: "area", item: area })}><Pencil size={14}/>تعديل</button><button className="icon-button admin-delete" onClick={() => setConfirmation({ id: area.id, kind: "area", action: "delete", label: area.name })} aria-label={`حذف ${area.name}`}><Trash2 size={15}/></button></div>)}<div className="form-notice"><MapPin size={23}/><span>اختيار «عنوان آخر» موجود تلقائيًا، وبيظهر بعده تكست بوكس صغير لكتابة العنوان.</span></div></div>}
    {tab === "advertisements" && <CampaignManagement ads={filteredAds} categories={data.categories} moderator={isModerator} busy={busy} onEdit={(ad) => setEditing({ kind: "ad", item: ad })} onApprove={(ad) => setConfirmation({ id: ad.id, kind: "ad", action: "approve", label: ad.businessName, price: ad.price })} onDelete={(ad) => setConfirmation({ id: ad.id, kind: "ad", action: "delete", label: ad.businessName })} onAction={(ad, action) => { void mutate("PATCH", { type: "ad", id: ad.id, action }, "تم تحديث حالة الحملة."); }}/>}
    {tab === "members" && <><div className="member-count-banner"><UsersRound size={31}/><div><strong>{data.memberCount} عضو مسجل في الموقع</strong><span>لا يشمل حساب الأدمن، ولا يمثل عدد المهنيين.</span></div></div><div className="admin-member-list">{filteredMembers.map((member) => <article className="admin-member-row" key={member.id}><span className="member-row-avatar"><UserRound size={23}/></span><div><h3>{member.name}<span className={`status-badge ${member.active ? "status-approved" : "status-rejected"}`}>{member.active ? "نشط" : "موقوف"}</span>{member.role === "moderator" && <span className="status-badge status-approved">مشرف</span>}</h3><p><span dir="ltr">@{member.username}</span><span dir="ltr">{member.phone}</span><span>انضم {new Date(member.createdAt).toLocaleDateString("ar-EG")}</span></p></div><div className="member-row-actions"><button className="button button-soft button-small" onClick={() => setEditing({ kind: "member", item: member })}><Pencil size={14}/>تعديل</button><button className={`button button-small ${member.active ? "button-danger-soft" : "button-success"}`} disabled={busy === member.id} onClick={() => mutate("PATCH", { type: "member", id: member.id, values: { active: !member.active } }, member.active ? "تم إيقاف العضوية وإنهاء جلساتها." : "تم تفعيل العضوية.")}>{member.active ? "إيقاف" : "تفعيل"}</button><button className="icon-button admin-delete" onClick={() => setConfirmation({ id: member.id, kind: "member", action: "delete", label: member.name })} aria-label={`حذف العضو ${member.name}`}><Trash2 size={15}/></button></div></article>)}{!filteredMembers.length && <AdminEmpty title="لسه مفيش أعضاء هنا" text="أي تسجيل جديد هيظهر كعضوية مستقلة هنا، وليس كمهنة في الدليل."/>}</div></>}
    {tab === "notifications" && <><div className="notification-tools"><button className="button button-soft button-small" onClick={() => mutate("PATCH", { type: "notification", action: "read-all" }, "تم تحديد كل الإشعارات كمقروءة.")}><CheckCheck size={17}/>تحديد الكل كمقروء</button>{data.notifications.length > 0 && <><button className="button button-soft button-small" aria-pressed={notificationSelectionMode} onClick={() => { setNotificationSelectionMode(!notificationSelectionMode); setSelectedNotificationIds(new Set()); }}>{notificationSelectionMode ? "إلغاء التحديد" : "تحديد"}</button>{notificationSelectionMode && <><button className="button button-soft button-small notification-select-all" onClick={toggleAllNotifications}>{allNotificationsSelected ? "إلغاء تحديد الكل" : "تحديد الكل"}</button>{selectedNotificationIds.size > 0 && <button className="button button-danger-soft button-small" onClick={() => setBulkDeleteConfirmation({ ids: [...selectedNotificationIds], deleteAll: allNotificationsSelected })}><Trash2 size={16}/>{allNotificationsSelected ? "حذف الكل" : `حذف المحدد (${selectedNotificationIds.size})`}</button>}</>}</>}{permission !== "unsupported" && <button className="button button-soft button-small" onClick={enableNotifications} disabled={permission === "granted"}><BellRing size={17}/>{permission === "granted" ? "تنبيهات المتصفح مفعّلة" : "تفعيل تنبيهات المتصفح"}</button>}</div><p className="notification-help">الطلبات تُفحص كل ١٠ ثوانٍ أثناء فتح اللوحة. إشعارات المتصفح تحتاج إذنك، وإشعارات اللوحة متاحة دائمًا.</p><div className="notifications-list">{data.notifications.map((notification) => <article key={notification.id} className={`notification-row ${notification.read ? "" : "notification-unread"} ${selectedNotificationIds.has(notification.id) ? "notification-row-selected" : ""}`}>{notificationSelectionMode && <label className="notification-row-checkbox"><input type="checkbox" checked={selectedNotificationIds.has(notification.id)} onChange={() => toggleNotificationSelection(notification.id)} aria-label={`تحديد إشعار: ${notification.title}`}/></label>}<span className="notification-type-icon">{notification.type === "service" ? <FileClock size={23}/> : notification.type === "ad" ? <Megaphone size={23}/> : <UserRound size={23}/>}</span><div><h3>{notification.title}{!notification.read && <span>جديد</span>}</h3><p>{notification.message}</p><small>{new Date(notification.createdAt).toLocaleString("ar-EG")}</small></div><button className="button button-soft button-small" onClick={() => openNotification(notification)}>عرض<ChevronLeft size={14}/></button></article>)}{!data.notifications.length && <AdminEmpty title="مفيش إشعارات حاليًا" text="طلبات المهن والإعلانات والتسجيلات الجديدة ستظهر هنا تلقائيًا."/>}</div></>}
    {tab === "settings" && <SettingsEditor key="full-settings" settings={data.settings} onSave={(values) => mutate("PATCH", { type: "settings", values }, "تم حفظ إعدادات الموقع ومحتواه.")}/>}
    {tab === "import" && <AdminImport data={data} onImported={() => { void mutate("GET", undefined, "تم تحديث طلبات المعامل."); }}/>}
    </section><footer className="admin-footer">© {new Date().getFullYear()} {data.settings.copyright}<span><LockKeyhole size={13}/>{isModerator ? "مشرف بصلاحيات محدودة • جلسة محمية" : "أدمن فقط • جلسة محمية"}</span></footer></main>
    {toast && <div className={`admin-toast ${toast.error ? "toast-error" : ""}`} role={toast.error ? "alert" : "status"}>{toast.error ? <CircleX size={20}/> : <CheckCircle2 size={20}/>}<span>{toast.text}</span><button onClick={() => setToast(null)} aria-label="إغلاق التنبيه"><X size={16}/></button></div>}
    {editing && <Modal title={editorTitle} subtitle="كل التعديلات محفوظة في قاعدة بيانات الموقع" onClose={closeEditor} wide={editing.kind === "service" || editing.kind === "category" || editing.kind === "ad"}><ManagementEditor key={`${editing.kind}-${editing.item?.id ?? "new"}`} editing={editing} data={data} onSave={saveEditor}/></Modal>}
    {confirmation && <Modal title={confirmation.action === "delete" ? "حذف نهائي؟" : "تأكيد الدفع وتفعيل الإعلان"} onClose={closeConfirmation}><div className="confirmation-content"><span className={confirmation.action === "delete" ? "confirm-delete-icon" : "confirm-pay-icon"}>{confirmation.action === "delete" ? <Trash2 size={32}/> : <Megaphone size={34}/>}</span><h3>{confirmation.label}</h3><p>{confirmation.action === "delete" ? "الحذف نهائي ولا يمكن التراجع عنه. التصنيف أو العنوان المرتبط بمهن لا يُحذف قبل نقلها، ويمكن إخفاء التصنيف بدل حذفه." : `أنت بتؤكد استلام ${confirmation.price} جنيه من العميل. الإعلان هيظهر حسب الجدولة المحددة. الطلبات الجديدة بدون جدولة تُنشر لمدة ${data.settings.adDays} أيام.`}</p><div className="confirmation-buttons"><button className={`button ${confirmation.action === "delete" ? "button-danger" : "button-success"}`} disabled={busy === confirmation.id} onClick={async () => { if (confirmation.action === "approve") await change(confirmation.id, "ad", "approve"); else if (await mutate("DELETE", { id: confirmation.id, type: confirmation.kind }, "تم الحذف نهائيًا.")) setConfirmation(null); }}>{busy === confirmation.id ? <LoaderCircle size={18} className="spin"/> : <Check size={18}/>} {confirmation.action === "delete" ? "نعم، احذف نهائيًا" : "تم استلام المبلغ، انشر الإعلان"}</button><button className="button button-soft" onClick={closeConfirmation}>إلغاء</button></div></div></Modal>}
    {bulkDeleteConfirmation && <Modal title="حذف الإشعارات؟" onClose={() => setBulkDeleteConfirmation(null)}><div className="confirmation-content"><span className="confirm-delete-icon"><Trash2 size={32}/></span><h3>{bulkDeleteConfirmation.deleteAll ? "كل الإشعارات" : `${bulkDeleteConfirmation.ids.length} إشعار`}</h3><p>الحذف نهائي ولا يمكن التراجع عنه.</p><div className="confirmation-buttons"><button className="button button-danger" disabled={busy === "saving"} onClick={() => void deleteBulkNotifications()}>{busy === "saving" ? <LoaderCircle size={18} className="spin"/> : <Trash2 size={18}/>} {bulkDeleteConfirmation.deleteAll ? "نعم، احذف الكل" : "نعم، احذف المحدد"}</button><button className="button button-soft" onClick={() => setBulkDeleteConfirmation(null)}>إلغاء</button></div></div></Modal>}
  </div>;
}
function AdminEmpty({ title, text }: { title: string; text: string }) { return <div className="empty-state admin-empty"><span><FileClock size={36}/></span><h3>{title}</h3><p>{text}</p></div>; }
