"use client";

import { useState } from "react";
import { Check, EllipsisVertical, Pause, Pencil, Play, Trash2, X } from "lucide-react";
import { adCtr, adPlacementOptions, adTypeOptions, type AdRecord, type CategoryRecord } from "@/lib/catalog";
import AdminActionSheet, { type AdminSheetItem } from "@/components/admin-action-sheet";

type Props = { ads: AdRecord[]; categories: CategoryRecord[]; moderator: boolean; busy: string | null; onEdit: (ad: AdRecord) => void; onApprove: (ad: AdRecord) => void; onDelete: (ad: AdRecord) => void; onAction: (ad: AdRecord, action: "pause" | "resume" | "reject") => void };
function state(ad: AdRecord) { if (ad.campaignStatus === "paused") return "paused"; if (ad.expiresAt && Date.parse(ad.expiresAt) <= Date.now()) return "expired"; if (ad.startsAt && Date.parse(ad.startsAt) > Date.now()) return "scheduled"; return "active"; }
const labels: Record<string, string> = { active: "Active — نشط", paused: "Paused — متوقف مؤقتًا", scheduled: "مجدول", expired: "منتهي" };
const review: Record<string, string> = { pending: "قيد المراجعة", approved: "موافق عليه", rejected: "مرفوض" };
function date(value: string | null) { return value ? new Date(value).toLocaleString("ar-EG") : "غير محدد"; }
export default function CampaignManagement({ ads, categories, moderator, busy, onEdit, onApprove, onDelete, onAction }: Props) {
  const [placement, setPlacement] = useState(""), [campaignState, setCampaignState] = useState("");
  const [menu, setMenu] = useState<{ title: string; subtitle: string; items: AdminSheetItem[] } | null>(null);
  const filtered = ads.filter((ad) => (!placement || ad.placement === placement) && (!campaignState || state(ad) === campaignState));
  const impressions = filtered.reduce((n, ad) => n + ad.impressions, 0), clicks = filtered.reduce((n, ad) => n + ad.clicks, 0);
  // Mobile action sheet for an ad card. The list is built when the menu opens (event handler), not during render.
  function openMenu(ad: AdRecord) { setMenu({ title: ad.name || ad.businessName, subtitle: review[ad.status], items: menuItems(ad) }); }
  function menuItems(ad: AdRecord): AdminSheetItem[] {
    const items: AdminSheetItem[] = [];
    if (!moderator) items.push({ id: "edit", label: "تعديل", icon: <Pencil size={17}/>, onSelect: () => onEdit(ad) }, { id: "pause", label: ad.campaignStatus === "paused" ? "استئناف" : "إيقاف مؤقت", icon: ad.campaignStatus === "paused" ? <Play size={17}/> : <Pause size={17}/>, onSelect: () => onAction(ad, ad.campaignStatus === "paused" ? "resume" : "pause") });
    if (ad.status !== "approved") items.push({ id: "approve", label: "تأكيد الدفع والنشر", icon: <Check size={17}/>, tone: "success", onSelect: () => onApprove(ad) });
    if (ad.status !== "rejected") items.push({ id: "reject", label: "رفض الإعلان", icon: <X size={17}/>, tone: "danger", onSelect: () => onAction(ad, "reject") });
    if (!moderator) items.push({ id: "delete", label: "حذف", icon: <Trash2 size={17}/>, tone: "danger", onSelect: () => onDelete(ad) });
    return items;
  }
  return <div className="campaign-management"><div className="campaign-metrics"><div><span>عدد الظهور</span><strong>{impressions.toLocaleString("ar-EG")}</strong></div><div><span>عدد الضغطات</span><strong>{clicks.toLocaleString("ar-EG")}</strong></div><div><span>CTR — نسبة الضغط</span><strong dir="ltr">{adCtr(impressions, clicks).toFixed(2)}%</strong></div></div><p className="campaign-field-help">الظهور: نصف الإعلان ظاهر لمدة ثانية، مرة لكل إعلان في زيارة الصفحة. الضغطات: اتصال أو واتساب أو تفاصيل. CTR = الضغطات ÷ الظهور × ١٠٠. ليست إحصاءات زوار فريدة أو أساسًا للفوترة.</p>
    <div className="campaign-filters"><label>مكان العرض<select value={placement} onChange={(e) => setPlacement(e.target.value)}><option value="">كل الأماكن</option>{adPlacementOptions.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>حالة التشغيل<select value={campaignState} onChange={(e) => setCampaignState(e.target.value)}><option value="">كل الحالات</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
    <div className="admin-ad-list">{filtered.map((ad) => <article key={ad.id} className="admin-ad-row campaign-admin-row"><div className="admin-ad-title"><div><h3>{ad.name || ad.businessName}</h3><p>{ad.businessName} · {adTypeOptions.find((o) => o.id === ad.adType)?.label} · {adPlacementOptions.find((o) => o.id === ad.placement)?.label}</p></div><span className={`status-badge status-${ad.status}`}>{review[ad.status]}</span><span className={`status-badge ${state(ad) === "active" ? "status-approved" : "status-rejected"}`}>{labels[state(ad)]}</span></div><blockquote>{ad.text}</blockquote><div className="campaign-admin-info"><span>القسم: {categories.find((c) => c.id === ad.categoryId)?.name || "بدون استهداف"}</span><span>الأولوية: {ad.priority}</span><span>البداية: {date(ad.startsAt)}</span><span>النهاية: {date(ad.expiresAt)}</span><span>{ad.paid ? "الدفع مؤكد" : "بانتظار الدفع"} · {ad.price} جنيه</span></div><div className="campaign-ad-metrics"><span>الظهور <strong>{ad.impressions.toLocaleString("ar-EG")}</strong></span><span>الضغطات <strong>{ad.clicks.toLocaleString("ar-EG")}</strong></span><span>CTR <strong dir="ltr">{adCtr(ad.impressions, ad.clicks).toFixed(2)}%</strong></span></div><div className="campaign-admin-actions">{!moderator && <><button type="button" className="button button-soft button-small" onClick={() => onEdit(ad)}>تعديل</button><button type="button" className="button button-soft button-small" disabled={busy === ad.id} onClick={() => onAction(ad, ad.campaignStatus === "paused" ? "resume" : "pause")}>{ad.campaignStatus === "paused" ? "استئناف" : "إيقاف مؤقت"}</button></>}{ad.status !== "approved" && <button type="button" className="button button-success button-small" disabled={busy === ad.id} onClick={() => onApprove(ad)}>تأكيد الدفع والنشر</button>}{ad.status !== "rejected" && <button type="button" className="button button-danger-soft button-small" disabled={busy === ad.id} onClick={() => onAction(ad, "reject")}>رفض الإعلان</button>}{!moderator && <button type="button" className="button button-danger-soft button-small" disabled={busy === ad.id} onClick={() => onDelete(ad)}>حذف</button>}</div><div className="admin-card-footer">{ad.status !== "approved" ? <button type="button" className="button button-success button-small" disabled={busy === ad.id} onClick={() => onApprove(ad)}>تأكيد الدفع والنشر</button> : !moderator && <button type="button" className="button button-soft button-small" onClick={() => onEdit(ad)}>تعديل</button>}<button type="button" className="button button-soft button-small admin-card-menu-button" aria-haspopup="dialog" aria-label={`إجراءات ${ad.name || ad.businessName}`} onClick={() => openMenu(ad)}><EllipsisVertical size={17}/>إجراءات</button></div></article>)}{!filtered.length && <div className="empty-state"><h3>مفيش إعلانات مطابقة</h3><p>غيّر الفلاتر أو أضف حملة جديدة.</p></div>}</div>
  {menu && <AdminActionSheet title={menu.title} subtitle={menu.subtitle} items={menu.items} onClose={() => setMenu(null)}/>}
  </div>;
}
