"use client";

import { useState } from "react";
import { CampaignPreview } from "@/components/advertising";
import { adTypeOptions, adPlacementOptions, adIconOptions, type AdRecord, type CategoryRecord, type SiteSettings } from "@/lib/catalog";
import SelectField from "@/components/select-field";

function localDate(iso: string | null) { if (!iso) return ""; const date = new Date(iso); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export default function CampaignFields({ initial, categories, settings }: { initial: Partial<AdRecord>; categories: CategoryRecord[]; settings: SiteSettings }) {
  const [ad, setAd] = useState<AdRecord>({ id: "preview", name: "", businessName: "", text: "", phone: "", whatsappPhone: "", categoryId: "", adType: "banner", placement: "hero", videoUrl: "", destinationUrl: "", imageUrl: "", offerText: "", startsAt: null, expiresAt: null, campaignStatus: "active", priority: 0, status: "pending", price: settings.adPrice, paid: false, backgroundColor: "#ccecff", icon: "Store", textSize: 17, highlightWord: "", motion: "static", impressions: 0, clicks: 0, createdAt: "", ...initial });
  const [preview, setPreview] = useState(false);
  function update(key: keyof AdRecord, value: string | number | boolean | null) { setAd((old) => ({ ...old, [key]: value })); }
  return <>
    <div className="form-notice notice-amber">النشر يتطلب مراجعة الإعلان وتأكيد استلام المقابل. الإيقاف المؤقت يحافظ على البيانات والإحصاءات.</div>
    <div className="form-row"><label className="field">اسم الإعلان (داخلي)<input name="name" value={ad.name || ""} onChange={(e) => update("name", e.target.value)} maxLength={160} required/></label><label className="field">اسم المعلن<input name="businessName" value={ad.businessName} onChange={(e) => update("businessName", e.target.value)} minLength={3} maxLength={160} required/></label></div>
    <label className="field">نص الإعلان<textarea name="text" value={ad.text} onChange={(e) => update("text", e.target.value)} minLength={10} maxLength={300} rows={3} required/></label>
    <label className="field">السعر أو العرض الظاهر للزوار (اختياري)<input name="offerText" value={ad.offerText} onChange={(e) => update("offerText", e.target.value)} maxLength={100} placeholder="خصم ٢٠٪ على الأدوات المدرسية"/></label>
    <div className="form-row"><label className="field">نوع المحتوى<SelectField name="adType" value={ad.adType} onChange={(e) => update("adType", e.target.value)}>{adTypeOptions.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}</SelectField></label><label className="field">مكان العرض<SelectField name="placement" value={ad.placement} onChange={(e) => update("placement", e.target.value)}>{adPlacementOptions.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}</SelectField></label></div>
    <label className="field">القسم أو التخصص<SelectField name="categoryId" value={ad.categoryId} required={ad.placement === "inline"} onChange={(e) => update("categoryId", e.target.value)}><option value="">بدون استهداف قسم (الرئيسية / المميزين)</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.parentId ? "↳ " : ""}{c.name}{!c.active && " (مخفي)"}</option>)}</SelectField><small>إعلان النتائج يظهر في قسمه وتخصصاته؛ استهداف تخصص واحد لا يظهر في التخصصات الأخرى.</small></label>
    <label className="field">صورة الإعلان<input name="imageUrl" value={ad.imageUrl} onChange={(e) => update("imageUrl", e.target.value)} dir="ltr" maxLength={1000} placeholder="https://… أو /images/…"/><small>رابط HTTPS أو صورة داخل الموقع. بدون صورة تظهر أيقونة النشاط.</small></label>
    <label className="field">الفيديو {ad.adType === "video" ? "(مطلوب)" : "(اختياري)"}<input name="videoUrl" value={ad.videoUrl} onChange={(e) => update("videoUrl", e.target.value)} dir="ltr" maxLength={1000} required={ad.adType === "video"} placeholder="https://example.com/ad.mp4"/><small>ملف MP4 / WebM / Ogg مباشر؛ ليس رابط يوتيوب. التشغيل باختيار الزائر.</small></label>
    <label className="field">رابط صفحة المعلن / عرض التفاصيل<input name="destinationUrl" value={ad.destinationUrl} onChange={(e) => update("destinationUrl", e.target.value)} dir="ltr" maxLength={1000} required={ad.placement === "sponsored"} placeholder="/categories/crafts أو https://…"/></label>
    <div className="form-row"><label className="field">رقم الهاتف<input name="phone" value={ad.phone} onChange={(e) => update("phone", e.target.value)} dir="ltr" type="tel" maxLength={24} required/></label><label className="field">رقم WhatsApp (اختياري)<input name="whatsappPhone" value={ad.whatsappPhone} onChange={(e) => update("whatsappPhone", e.target.value)} dir="ltr" type="tel" maxLength={24}/><small>فارغ = استخدام رقم الهاتف.</small></label></div>
    <div className="form-row"><label className="field">تاريخ البداية<input name="startsAt" type="datetime-local" dir="ltr" defaultValue={localDate(ad.startsAt)}/></label><label className="field">تاريخ النهاية<input name="expiresAt" type="datetime-local" dir="ltr" defaultValue={localDate(ad.expiresAt)}/></label></div>
    <p className="campaign-field-help">المواعيد بتوقيت جهازك. بداية فارغة = فور النشر؛ نهاية فارغة = بدون انتهاء.</p>
    <div className="form-row"><label className="field">الأولوية<input name="priority" type="number" value={ad.priority} onChange={(e) => update("priority", Number(e.target.value))} min={0} max={1000} required/><small>الرقم الأكبر يظهر أولًا.</small></label><label className="field">حالة التشغيل<SelectField name="campaignStatus" value={ad.campaignStatus} onChange={(e) => update("campaignStatus", e.target.value)}><option value="active">Active — نشط</option><option value="paused">Paused — متوقف مؤقتًا</option></SelectField></label></div>
    <div className="form-row"><label className="field">حالة المراجعة<SelectField name="status" value={ad.status} onChange={(e) => update("status", e.target.value)}><option value="pending">قيد المراجعة</option><option value="approved">موافق عليه</option><option value="rejected">مرفوض</option></SelectField></label><label className="field">سعر حجز الإعلان بالجنيه<input name="price" type="number" value={ad.price} onChange={(e) => update("price", Number(e.target.value))} min={0} max={100000} required/></label></div>
    <label className="checkbox-field"><input name="paid" type="checkbox" checked={ad.paid} onChange={(e) => update("paid", e.target.checked)}/>تم استلام المقابل المالي / إعلان المكتب المجاني</label>
    <div className="form-row"><label className="field">لون الإعلان<input name="backgroundColor" type="color" value={ad.backgroundColor || "#ccecff"} onChange={(e) => update("backgroundColor", e.target.value)}/></label><label className="field">أيقونة بديلة<SelectField name="icon" value={ad.icon || "Store"} onChange={(e) => update("icon", e.target.value)}>{adIconOptions.map((o) => <option key={o.icon} value={o.icon}>{o.label}</option>)}</SelectField></label></div>
    <input type="hidden" name="motion" value={ad.motion}/><input type="hidden" name="textSize" value={ad.textSize}/><input type="hidden" name="highlightWord" value={ad.text.includes(ad.highlightWord) ? ad.highlightWord : ""}/>
    <button type="button" className="button button-soft" aria-expanded={preview} onClick={() => setPreview((v) => !v)}>{preview ? "إخفاء المعاينة" : "معاينة الإعلان"}</button>
    {preview && <CampaignPreview ad={{ ...ad, businessName: ad.businessName || "اسم المعلن", text: ad.text || "نص الإعلان هيظهر هنا، مع وسائل التواصل الخاصة بالمعلن." }}/>}<p className="campaign-field-help">المعاينة لا تحسب ظهورًا أو ضغطات.</p>
  </>;
}
