"use client";

import { useState, type FormEvent } from "react";
import { LoaderCircle, Save } from "lucide-react";
import CampaignFields from "@/components/campaign-fields";
import { AddressFields } from "@/components/request-forms";
import { getCategory, iconNames, type AdRecord, type AdminDirectory, type AreaRecord, type CategoryRecord, type MemberRecord, type ServiceRecord } from "@/lib/catalog";
import SelectField from "@/components/select-field";

export type EntityKind = "service" | "ad" | "category" | "area" | "member";
export type EditorState = { kind: EntityKind; item?: ServiceRecord | AdRecord | CategoryRecord | AreaRecord | MemberRecord; parentId?: string };
export default function ManagementEditor({ editing, data, onSave }: { editing: EditorState; data: AdminDirectory; onSave: (values: Record<string, unknown>) => Promise<boolean> }) {
  const record = (editing.item ?? {}) as Partial<ServiceRecord & AdRecord & CategoryRecord & AreaRecord & MemberRecord>;
  const roots = data.categories.filter((category) => !category.parentId);
  const [root, setRoot] = useState(record.category ? getCategory(record.category, data.categories).parentId ?? "" : "");
  const [specialty, setSpecialty] = useState(record.category ?? ""), [color, setColor] = useState(record.color ?? "#0876e1");
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const form = new FormData(event.currentTarget), values: Record<string, unknown> = Object.fromEntries(form);
    for (const key of ["verified", "featured", "emergency", "paid", "active", "demo"]) values[key] = form.get(key) === "on";
    try {
      if (editing.kind === "ad") for (const key of ["startsAt", "expiresAt"]) values[key] = form.get(key) ? new Date(String(form.get(key))).toISOString() : null;
      if (!(await onSave(values))) setError("لم يتم الحفظ. راجع رسالة الخطأ وصحّح البيانات.");
    }
    catch { setError("تعذر حفظ البيانات. حاول مرة أخرى."); }
    finally { setBusy(false); }
  }
  return <form className="request-form management-form" onSubmit={submit}>
    {editing.kind === "service" && <><label className="field">اسم مقدم الخدمة<input name="name" defaultValue={record.name} required minLength={3} maxLength={160}/></label><div className="form-row"><label className="field">التصنيف الرئيسي<SelectField value={root} onChange={(event) => { setRoot(event.target.value); setSpecialty(""); }} required><option value="" disabled>اختار القسم</option>{roots.map((category) => <option key={category.id} value={category.id}>{category.name}{!category.active && " (مخفي)"}</option>)}</SelectField></label><label className="field">المهنة أو التخصص<SelectField name="category" value={specialty} onChange={(event) => setSpecialty(event.target.value)} required disabled={!root}><option value="" disabled>اختار التخصص</option>{data.categories.filter((category) => category.parentId === root).map((category) => <option key={category.id} value={category.id}>{category.name}{!category.active && " (مخفي)"}</option>)}</SelectField></label></div><AddressFields areaOptions={data.areas} initialArea={record.area} initialAddress={record.address} editableDetails/><label className="field">رقم الهاتف<input name="phone" defaultValue={record.phone} required type="tel" dir="ltr" maxLength={16}/></label><label className="field">رقم هاتف إضافي<input name="phoneSecondary" defaultValue={record.phoneSecondary} type="tel" dir="ltr" maxLength={16}/></label><label className="field">وصف الخدمة<textarea name="description" defaultValue={record.description} required minLength={10} maxLength={1000} rows={3}/></label><label className="field">حالة النشر<SelectField name="status" defaultValue={record.status ?? "approved"}><option value="pending">قيد المراجعة</option><option value="approved">منشور</option><option value="rejected">مرفوض / موقوف</option></SelectField></label><div className="editor-checkboxes"><label className="checkbox-field"><input type="checkbox" name="verified" defaultChecked={record.verified ?? true}/> موثقة</label><label className="checkbox-field"><input type="checkbox" name="featured" defaultChecked={record.featured}/> خدمة مميزة</label><label className="checkbox-field"><input type="checkbox" name="emergency" defaultChecked={record.emergency}/> متاح للطوارئ</label><label className="checkbox-field"><input type="checkbox" name="demo" defaultChecked={record.demo}/> بطاقة توضيحية</label></div></>}
    {editing.kind === "ad" && <CampaignFields initial={record} categories={data.categories} settings={data.settings}/>}
    {editing.kind === "category" && <><label className="field">اسم التصنيف أو التخصص<input name="name" defaultValue={record.name} required minLength={2} maxLength={100}/></label><label className="field">ينتمي إلى<SelectField name="parentId" defaultValue={record.parentId ?? editing.parentId ?? ""}><option value="">تصنيف رئيسي</option>{roots.filter((category) => category.id !== record.id).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</SelectField></label>{!editing.item && <label className="field">رابط التصنيف (اختياري)<input name="slug" dir="ltr" placeholder="مثال: new-specialty" maxLength={60}/><small className="input-help">لو تركته فارغًا، الموقع هيختار رابطًا فريدًا تلقائيًا.</small></label>}<label className="field">وصف مختصر<textarea name="description" defaultValue={record.description} maxLength={240} rows={2}/></label><div className="form-row"><label className="field">لون التصنيف<div className="color-editor"><input type="color" name="color" value={color} onChange={(event) => setColor(event.target.value)}/><span dir="ltr">{color}</span></div></label><label className="field">الأيقونة<SelectField name="icon" defaultValue={record.icon ?? "Wrench"}>{iconNames.map((icon) => <option key={icon}>{icon}</option>)}</SelectField></label></div><label className="field">ترتيب الظهور<input name="sortOrder" type="number" defaultValue={record.sortOrder ?? 0} min={0} max={1000} required/></label><label className="checkbox-field"><input name="active" type="checkbox" defaultChecked={record.active ?? true}/> ظاهر في الموقع (إخفاء التصنيف يُخفي خدماته دون حذفها)</label></>}
    {editing.kind === "area" && <><label className="field">اسم العنوان<input name="name" defaultValue={record.name} placeholder="جنزور / اسم الشارع أو الناحية" required minLength={3} maxLength={80}/></label><label className="field">ترتيب الظهور<input name="sortOrder" type="number" defaultValue={record.sortOrder ?? 0} required min={0} max={1000}/></label><div className="form-notice"><span>تعديل اسم العنوان يحدّث العناوين المرتبطة بالمهن تلقائيًا. اختيار «عنوان آخر» موجود دائمًا.</span></div></>}
    {editing.kind === "member" && <><div className="form-notice"><span>يمكنك منح العضو صلاحية مشرف محدودة أو إعادته إلى عضوية عادية. إعدادات الموقع وإدارة الأعضاء تظل للأدمن فقط.</span></div><label className="field">اسم العضو<input name="name" defaultValue={record.name} required minLength={3} maxLength={120}/></label><label className="field">اسم المستخدم<input defaultValue={record.username} readOnly dir="ltr"/></label><label className="field">رقم الهاتف<input name="phone" defaultValue={record.phone} required type="tel" dir="ltr" maxLength={16}/></label><label className="field">صلاحية العضو<SelectField name="role" defaultValue={record.role ?? "member"}><option value="member">عضو</option><option value="moderator">مشرف بصلاحيات محدودة</option></SelectField><small className="input-help">المشرف يراجع الطلبات والإعلانات، ويُدير التصنيفات والإشعارات فقط.</small></label><label className="checkbox-field"><input name="active" type="checkbox" defaultChecked={record.active}/> عضوية نشطة (إيقافها يُنهي جلسات دخول العضو)</label></>}
    {error && <div className="form-error" role="alert">{error}</div>}<button className="button button-primary form-submit" type="submit" disabled={busy}>{busy ? <LoaderCircle size={18} className="spin"/> : <Save size={18}/>} {busy ? "جاري الحفظ..." : "حفظ التعديلات"}</button>
  </form>;
}

