"use client";

import { useState, type FormEvent } from "react";
import { Check, CheckCircle2, CirclePlus, Clock3, LoaderCircle, MapPin, MessageCircle, Send, ShieldCheck } from "lucide-react";
import { areas, defaultSettings, initialCategories, OTHER_ADDRESS, whatsappUrl, type AreaRecord, type CategoryRecord, type SiteSettings } from "@/lib/catalog";
import { AdvertisingIcon } from "@/components/ui";

type FormOptions = { catalog: CategoryRecord[]; areaOptions: AreaRecord[] };
export function AddressFields({ areaOptions, initialArea = "", initialAddress = "", editableDetails = false }: { areaOptions: AreaRecord[]; initialArea?: string; initialAddress?: string; editableDetails?: boolean }) {
  const known = areaOptions.some((area) => area.name === initialArea);
  const [area, setArea] = useState(initialArea ? known ? initialArea : OTHER_ADDRESS : "");
  return <div className="address-fields"><label className="field">العنوان في جنزور <span className="required">*</span><select name="area" value={area} onChange={(event) => setArea(event.target.value)} required><option value="" disabled>اختار العنوان</option>{areaOptions.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}<option value={OTHER_ADDRESS}>{OTHER_ADDRESS}</option></select></label>{area === OTHER_ADDRESS ? <label className="field custom-address-field">اكتب العنوان الآخر <span className="required">*</span><input name="address" placeholder="مثال: جنزور / بجوار المدرسة" defaultValue={initialArea && !known ? initialAddress : ""} required minLength={3} maxLength={240}/></label> : editableDetails ? <label className="field">العنوان بالتفصيل<input name="address" key={area} defaultValue={initialAddress || area} placeholder="تفاصيل أو علامة مميزة" maxLength={240}/></label> : <input type="hidden" name="address" value={area}/>}</div>;
}
export function ServiceForm({ catalog = initialCategories, areaOptions = areas.map((name, sortOrder) => ({ id: name, name, sortOrder })), initialCategory = "", initialArea = "", onClose }: Partial<FormOptions> & { initialCategory?: string; initialArea?: string; onClose: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [submitted, setSubmitted] = useState<{ id: string; message: string } | null>(null);
  const selected = catalog.find((category) => category.id === initialCategory);
  const [root, setRoot] = useState(selected?.parentId ?? (selected && !selected.parentId ? selected.id : ""));
  const [specialty, setSpecialty] = useState(selected?.parentId ? selected.id : "");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const form = new FormData(event.currentTarget);
    try {
      const response = await fetch("/api/services", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(form), emergency: form.get("emergency") === "on" }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "تعذر إرسال الطلب."); setSubmitted(result);
    } catch (err) { setError(err instanceof Error ? err.message : "تعذر الاتصال. حاول مرة أخرى."); }
    finally { setBusy(false); }
  }
  if (submitted) return <div className="success-state"><span className="success-icon"><CheckCircle2 size={42}/></span><h3>طلبك وصل.. وأهلًا بيك!</h3><p>{submitted.message}</p><div className="reference-number"><Clock3 size={17}/> قيد مراجعة الإدارة <span dir="ltr">#{submitted.id.slice(0, 8)}</span></div><button className="button button-primary" onClick={onClose}>تمام، شكرًا <Check size={18}/></button></div>;
  return <form className="request-form" onSubmit={submit}><div className="form-notice"><ShieldCheck size={22}/><span>ده طلب إضافة خدمة، مش تسجيل عضوية. الطلب بيوصل للإدارة الأول ومش بيتنشر إلا بعد الموافقة.</span></div><label className="field">اسم مقدم الخدمة أو النشاط <span className="required">*</span><input name="name" placeholder="مثال: وائل سمير للنجارة" required minLength={3} maxLength={160}/></label><div className="form-row"><label className="field">التصنيف الرئيسي <span className="required">*</span><select value={root} onChange={(event) => { setRoot(event.target.value); setSpecialty(""); }} required><option value="" disabled>اختار التصنيف</option>{catalog.filter((category) => !category.parentId && category.active).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="field">المهنة أو التخصص <span className="required">*</span><select name="category" value={specialty} onChange={(event) => setSpecialty(event.target.value)} required disabled={!root}><option value="" disabled>{root ? "اختار التخصص" : "اختار التصنيف الأول"}</option>{catalog.filter((category) => category.parentId === root && category.active).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><AddressFields areaOptions={areaOptions} initialArea={initialArea}/><label className="field">رقم الهاتف / واتساب <span className="required">*</span><input name="phone" type="tel" inputMode="tel" dir="ltr" placeholder="01xxxxxxxxx" required maxLength={16}/></label><label className="field">رقم هاتف إضافي<input name="phoneSecondary" type="tel" inputMode="tel" dir="ltr" placeholder="اختياري" maxLength={16}/></label><label className="field">وصف الخدمة <span className="required">*</span><textarea name="description" placeholder="عرّف أهل جنزور بالخدمة اللي بتقدمها وخبرتك..." required minLength={10} maxLength={1000} rows={3}/></label><label className="checkbox-field"><input name="emergency" type="checkbox"/><span>متاح لخدمات الطوارئ والمساعدة العاجلة</span></label>{error && <div role="alert" className="form-error">{error}</div>}<button type="submit" className="button button-primary form-submit" disabled={busy}>{busy ? <LoaderCircle size={20} className="spin"/> : <CirclePlus size={20}/>} {busy ? "جاري إرسال الطلب..." : "إرسال طلب إضافة مهنتك"}</button><p className="form-footnote">الإضافة مجانية. بيانات التواصل تُنشر فقط بعد موافقة الإدارة.</p></form>;
}
export function AdvertisementForm({ settings = defaultSettings, onClose }: { settings?: SiteSettings; onClose: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [text, setText] = useState(""), [business, setBusiness] = useState("");
  const [submitted, setSubmitted] = useState<{ id: string; message: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const data = new FormData(event.currentTarget);
    try { const response = await fetch("/api/advertisements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "تعذر إرسال الإعلان."); setSubmitted(result); }
    catch (err) { setError(err instanceof Error ? err.message : "تعذر الاتصال. حاول مرة أخرى."); } finally { setBusy(false); }
  }
  if (submitted) return <div className="success-state"><span className="success-icon"><CheckCircle2 size={42}/></span><h3>إعلانك وصل للإدارة!</h3><p>{submitted.message}</p><div className="reference-number"><Clock3 size={17}/> بانتظار المراجعة وتأكيد الدفع</div><a href={whatsappUrl(settings.phone, `أرغب في إتمام حجز إعلان ${business}، رقم الطلب ${submitted.id}، بقيمة ${settings.adPrice} جنيه لمدة ${settings.adDays} أيام.`)} target="_blank" rel="noopener noreferrer" className="button button-whatsapp"><MessageCircle size={19}/> إتمام الحجز عبر واتساب</a><button className="text-button" onClick={onClose}>العودة للدليل</button></div>;
  return <form className="request-form" onSubmit={submit}><div className="ad-plan"><AdvertisingIcon/><div><strong>شغلك قدّام كل أهل جنزور</strong><span>كارتك الإعلاني على الرئيسية لمدة {settings.adDays} أيام</span></div><div className="ad-plan-price"><strong>{settings.adPrice}<small> جنيه</small></strong><span>للحجز</span></div></div><label className="field">اسم النشاط <span className="required">*</span><input name="businessName" value={business} onChange={(event) => setBusiness(event.target.value)} placeholder="اسم شركتك أو مهنتك" required minLength={3} maxLength={160}/></label><label className="field">رقم الهاتف / واتساب <span className="required">*</span><input name="phone" type="tel" inputMode="tel" dir="ltr" placeholder="01xxxxxxxxx" required maxLength={16}/></label><label className="field">نص الإعلان <span className="required">*</span><textarea name="text" value={text} onChange={(event) => setText(event.target.value)} placeholder="اكتب عرضك أو الخدمة اللي بتقدمها باختصار..." required minLength={10} maxLength={300} rows={3}/><span className="character-count">{text.length} / 300</span></label><div className="form-notice notice-amber"><ShieldCheck size={21}/><span>الإعلان يُنشر بعد المراجعة وتأكيد الدفع مع مكتب الجمال. لا يتم تحصيل مبلغ من الموقع.</span></div>{error && <div role="alert" className="form-error">{error}</div>}<button type="submit" className="button button-primary form-submit" disabled={busy}>{busy ? <LoaderCircle size={20} className="spin"/> : <Send size={19}/>} {busy ? "جاري إرسال الإعلان..." : "إرسال الإعلان للمراجعة"}</button><p className="form-footnote">عندك سؤال؟ <a href={whatsappUrl(settings.phone)} target="_blank" rel="noopener noreferrer">تواصل معنا على واتساب</a></p></form>;
}
export function LocationPicker({ areaOptions, selected, onSelect }: { areaOptions: AreaRecord[]; selected: string; onSelect: (area: string, custom?: string) => void }) {
  const [query, setQuery] = useState(""), [other, setOther] = useState(false), [custom, setCustom] = useState("");
  return <div className="location-picker"><div className="form-notice"><MapPin size={20}/><span>الدليل مخصص لقرية جنزور. اختار الناحية أو الشارع المناسب.</span></div><input aria-label="ابحث عن عنوان" placeholder="ابحث عن عنوان في جنزور..." value={query} onChange={(event) => setQuery(event.target.value)}/><div className="location-options janzour-location-options"><button className={!selected ? "selected" : ""} onClick={() => onSelect("")}><MapPin size={16}/>كل عناوين جنزور</button>{areaOptions.filter((area) => area.name.includes(query)).map((area) => <button key={area.id} className={selected === area.name ? "selected" : ""} onClick={() => onSelect(area.name)}><MapPin size={16}/>{area.name}{selected === area.name && <Check size={15}/>}</button>)}<button className={other ? "selected" : ""} onClick={() => setOther(!other)}><MapPin size={16}/>{OTHER_ADDRESS}</button></div>{other && <form className="custom-location-form" onSubmit={(event) => { event.preventDefault(); onSelect(OTHER_ADDRESS, custom.trim()); }}><label className="field">اكتب العنوان الآخر<input value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="الشارع أو أقرب علامة مميزة" minLength={3} required maxLength={240}/></label><button className="button button-primary" type="submit">ابحث في العنوان</button></form>}</div>;
}
