import { chromium, expect } from "@playwright/test";
import assert from "node:assert/strict";
import fs from "node:fs";

// Custom dropdowns (SelectField) replace native selects: open the combobox, then click the option by its value.
async function pickValue(page, combobox, value) {
  await combobox.click();
  await page.locator(`[role="option"][data-value="${value}"]`).click();
}
const base = process.env.TEST_BASE_URL || "http://localhost:3000";
fs.mkdirSync(".qa", { recursive: true });
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
const guestContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const adminContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const memberContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await guestContext.newPage(), admin = await adminContext.newPage(), member = await memberContext.newPage();
const errors = []; for (const target of [page, admin, member]) target.on("pageerror", (error) => errors.push(error.message));
const suffix = Date.now().toString(36);
let serviceId, adId, memberId, rootId, specialtyId, savedSettings;
const serviceName = "اختبار واجهة - نجار جنزور";
const memberName = "عضو اختبار الواجهة";
try {
  const baseline = await (await guestContext.request.get(`${base}/api/services`)).json();
  await page.goto(base, { waitUntil: "networkidle" });
  await page.evaluate(() => document.fonts.ready);
  await expect(page.locator(".main-category-grid .category-tile")).toHaveCount(6);
  await expect(page.locator(".provider-card")).toHaveCount(4);
  assert.equal(await page.evaluate(() => getComputedStyle(document.body).fontSize), "15px");
  const strip = await page.locator(".advertising-strip").evaluate((element) => ({ color: getComputedStyle(element).backgroundColor, radius: parseFloat(getComputedStyle(element).borderRadius) }));
  assert.equal(strip.color, "rgb(14, 15, 17)"); assert.ok(strip.radius >= 13);
  await expect(page.locator(".advertising-label strong")).toHaveText("مساحة إعلانية");
  await expect(page.locator('.header-inner a[href="/admin"]')).toHaveCount(0);
  await page.screenshot({ path: ".qa/janzour-home-desktop.png", fullPage: true });
  await page.getByRole("link", { name: "الحرفيين", exact: true }).click();
  await expect(page).toHaveURL(`${base}/categories/crafts`);
  await expect(page.locator(".specialties-grid .category-tile")).toHaveCount(12);
  await page.screenshot({ path: ".qa/janzour-crafts.png", fullPage: true });
  await page.getByRole("link", { name: "النجارة", exact: true }).click();
  await expect(page).toHaveURL(`${base}/categories/crafts/carpentry`);
  await expect(page.locator(".provider-card h3")).toContainText(["أحمد للنجارة والديكور"]);
  await page.locator(".provider-detail-button").first().click();
  await expect(page.getByRole("dialog").locator('.detail-actions a[href^="tel:"]')).toHaveCount(1);
  await expect(page.getByRole("dialog").locator(".detail-address")).toContainText("جنزور");
  await page.keyboard.press("Escape");
  await page.goto(`${base}/categories/clinics`, { waitUntil: "networkidle" });
  await expect(page.locator(".specialties-grid .category-tile")).toHaveCount(9);
  await page.getByRole("link", { name: "طب الأسرة والباطنة", exact: true }).click();
  await expect(page.locator(".provider-card h3")).toHaveText("د. سارة أحمد");
  await page.screenshot({ path: ".qa/janzour-clinic.png", fullPage: true });
  for (const root of ["shops", "teachers", "charities", "other-services"]) { await page.goto(`${base}/categories/${root}`, { waitUntil: "networkidle" }); assert.ok(await page.locator(".specialties-grid .category-tile").count() > 0); }
  console.log("PASS: six primary sections lead to real specialty pages and provider/doctor details");
  await page.goto(base, { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "أضف كهربائي منازل للمفضلة", exact: true }).click();
  await page.locator(".main-nav").getByRole("button", { name: /المفضلة/ }).click();
  await expect(page.locator(".provider-card")).toHaveCount(1);
  await page.reload({ waitUntil: "networkidle" });
  await expect(page.getByRole("button", { name: "إزالة كهربائي منازل من المفضلة", exact: true })).toHaveAttribute("aria-pressed", "true");
  await pickValue(page, page.getByRole("combobox", { name: "اختر العنوان", exact: true }), "جنزور / بجوار مكتبة الجمال");
  await page.getByRole("searchbox").fill("نجاره"); await page.getByRole("button", { name: "ابحث الآن", exact: true }).click();
  await expect(page.locator(".provider-card h3")).toHaveText("أحمد للنجارة والديكور");
  await page.getByRole("button", { name: "مسح الفلاتر", exact: true }).click();
  await page.locator(".location-card button").click();
  await page.getByRole("dialog").getByRole("button", { name: "عنوان آخر", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".custom-location-form input")).toBeVisible();
  await page.keyboard.press("Escape");
  console.log("PASS: favorites persist, Arabic search works and other-address search reveals a textbox");
  await admin.goto(`${base}/login`, { waitUntil: "networkidle" });
  await admin.screenshot({ path: ".qa/janzour-login.png", fullPage: true });
  await admin.locator("[name=username]").fill("admin"); await admin.locator("[name=password]").fill("admin");
  await admin.getByRole("button", { name: "تسجيل الدخول", exact: true }).click();
  await admin.getByRole("heading", { name: /أهلًا بيك، يا مدير الدليل/ }).waitFor();
  await admin.screenshot({ path: ".qa/janzour-admin.png", fullPage: true });
  await page.bringToFront();
  await page.getByRole("button", { name: "أضف مهنتك", exact: true }).click();
  const form = page.getByRole("dialog");
  await form.locator("[name=name]").fill(serviceName);
  await pickValue(page, form.getByRole("combobox", { name: /التصنيف الرئيسي/ }), "crafts");
  await pickValue(page, form.locator(".ui-select:has([name=category]) [role=combobox]"), "carpentry");
  await pickValue(page, form.locator(".ui-select:has([name=area]) [role=combobox]"), "عنوان آخر");
  await expect(form.locator("[name=address]")).toBeVisible();
  await form.locator("[name=address]").fill("جنزور / بجوار مدرسة اختبار الواجهة");
  await form.locator("[name=phone]").fill("01012345678");
  await form.locator("[name=description]").fill("طلب اختبار للتأكد من إشعار الإدارة ومراجعتها قبل نشر بيانات مقدم الخدمة في جنزور.");
  await page.screenshot({ path: ".qa/janzour-other-address-form.png" });
  const submitted = page.waitForResponse((response) => response.url().endsWith("/api/services") && response.request().method() === "POST");
  await form.getByRole("button", { name: "إرسال طلب إضافة مهنتك", exact: true }).click();
  serviceId = (await (await submitted).json()).id;
  await expect(form.getByRole("heading", { name: "طلبك وصل.. وأهلًا بيك!", exact: true })).toBeVisible();
  assert.ok(!(await (await guestContext.request.get(`${base}/api/services`)).json()).services.some((service) => service.id === serviceId));
  await form.getByRole("button", { name: "تمام، شكرًا", exact: true }).click();
  await admin.bringToFront();
  await expect(admin.locator(".admin-toast")).toContainText("طلب مهنة جديد بانتظارك", { timeout: 20000 });
  const row = admin.locator(".admin-service-row").filter({ hasText: serviceName });
  await expect(row).toBeVisible();
  await row.getByRole("button", { name: "موافقة ونشر", exact: true }).click();
  await expect(row).toHaveCount(0);
  await admin.locator(".admin-sidebar nav").getByRole("button", { name: "الدليل المنشور", exact: true }).click();
  const publishedRow = admin.locator(".admin-service-row").filter({ hasText: serviceName });
  await publishedRow.getByRole("button", { name: "تعديل البيانات", exact: true }).click();
  await admin.getByRole("dialog").locator("[name=name]").fill(`${serviceName} - معدل`);
  await admin.getByRole("dialog").getByRole("button", { name: "حفظ التعديلات", exact: true }).click();
  await expect(admin.getByRole("dialog")).toHaveCount(0);
  assert.equal((await (await guestContext.request.get(`${base}/api/services`)).json()).services.find((service) => service.id === serviceId).name, `${serviceName} - معدل`);
  console.log("PASS: service request creates live admin notification, remains hidden until approval, and supports editing");
  await page.locator(".advertising-book").click();
  const adDialog = page.getByRole("dialog"); await adDialog.locator("[name=businessName]").fill("اختبار واجهة - إعلان جنزور");
  await adDialog.locator("[name=phone]").fill("01222355769"); await adDialog.locator("[name=text]").fill("إعلان اختبار للتحقق من مراجعة الإدارة وتأكيد الدفع قبل العرض في المساحة السوداء المتحركة.");
  const adSubmitted = page.waitForResponse((response) => response.url().endsWith("/api/advertisements") && response.request().method() === "POST");
  await adDialog.getByRole("button", { name: "إرسال الإعلان للمراجعة", exact: true }).click(); adId = (await (await adSubmitted).json()).id;
  await expect(adDialog.getByRole("heading", { name: "إعلانك وصل للإدارة!", exact: true })).toBeVisible();
  await adDialog.getByRole("button", { name: "العودة للدليل", exact: true }).click();
  await admin.bringToFront(); await admin.locator(".admin-sidebar nav").getByRole("button", { name: /المساحة الإعلانية/ }).click();
  await admin.getByRole("button", { name: "تحديث", exact: true }).click();
  const adRow = admin.locator(".admin-ad-row").filter({ hasText: "اختبار واجهة - إعلان جنزور" }); await expect(adRow).toBeVisible();
  await adRow.getByRole("button", { name: "تأكيد الدفع والنشر", exact: true }).click();
  await admin.getByRole("dialog").getByRole("button", { name: "تم استلام المبلغ، انشر الإعلان", exact: true }).click();
  await expect(admin.getByRole("dialog")).toHaveCount(0);
  assert.ok((await (await guestContext.request.get(`${base}/api/advertisements`)).json()).ads.find((ad) => ad.id === adId)?.paid);
  await admin.screenshot({ path: ".qa/janzour-admin-advertising.png", fullPage: true });
  await page.mouse.move(0, 0); const x1 = await page.locator(".marquee-track").evaluate((element) => new DOMMatrixReadOnly(getComputedStyle(element).transform).m41);
  await page.waitForTimeout(350); const x2 = await page.locator(".marquee-track").evaluate((element) => new DOMMatrixReadOnly(getComputedStyle(element).transform).m41); assert.ok(x2 > x1);
  console.log("PASS: ad payment confirmation and left-to-right movement in rounded black advertising strip");
  await admin.locator(".admin-sidebar nav").getByRole("button", { name: "التصنيفات والتخصصات", exact: true }).click();
  await admin.getByRole("button", { name: "تصنيف جديد", exact: true }).click();
  let editor = admin.getByRole("dialog"); await editor.locator("[name=name]").fill("قسم اختبار الواجهة"); await editor.locator("[name=slug]").fill(`qa-ui-${suffix}`);
  await editor.getByRole("button", { name: "حفظ التعديلات", exact: true }).click(); await expect(editor).toHaveCount(0);
  let catalog = await (await adminContext.request.get(`${base}/api/admin`)).json(); rootId = catalog.categories.find((category) => category.id === `qa-ui-${suffix}`).id;
  const group = admin.locator(".category-management-group").filter({ hasText: "قسم اختبار الواجهة" });
  await group.getByRole("button", { name: "تخصص", exact: true }).click(); editor = admin.getByRole("dialog");
  await editor.locator("[name=name]").fill("تخصص اختبار الواجهة"); await editor.locator("[name=slug]").fill(`qa-ui-specialty-${suffix}`);
  await editor.getByRole("button", { name: "حفظ التعديلات", exact: true }).click(); await expect(editor).toHaveCount(0);
  catalog = await (await adminContext.request.get(`${base}/api/admin`)).json(); specialtyId = catalog.categories.find((category) => category.id === `qa-ui-specialty-${suffix}`).id;
  assert.equal((await guestContext.request.get(`${base}/categories/${rootId}/${specialtyId}`)).status(), 200);
  await admin.getByRole("button", { name: "إخفاء تخصص اختبار الواجهة", exact: true }).click();
  await expect(admin.getByRole("button", { name: "إظهار تخصص اختبار الواجهة", exact: true })).toBeVisible();
  assert.ok(!(await (await guestContext.request.get(`${base}/api/services`)).json()).categories.some((category) => category.id === specialtyId));
  await admin.screenshot({ path: ".qa/janzour-admin-categories.png", fullPage: true });
  await adminContext.request.delete(`${base}/api/admin`, { data: { type: "category", id: specialtyId } }); specialtyId = undefined;
  await adminContext.request.delete(`${base}/api/admin`, { data: { type: "category", id: rootId } }); rootId = undefined;
  savedSettings = (await (await adminContext.request.get(`${base}/api/admin`)).json()).settings;
  await admin.locator(".admin-sidebar nav").getByRole("button", { name: "إعدادات الموقع", exact: true }).click();
  await admin.locator("[name=heroSubtitle]").fill("وصف اختبار من لوحة التحكم - أهل جنزور");
  await admin.getByRole("button", { name: "حفظ الإعدادات", exact: true }).click();
  await expect(admin.locator(".settings-saved")).toBeVisible();
  assert.equal((await (await guestContext.request.get(`${base}/api/services`)).json()).settings.heroSubtitle, "وصف اختبار من لوحة التحكم - أهل جنزور");
  await adminContext.request.patch(`${base}/api/admin`, { data: { type: "settings", values: savedSettings } }); savedSettings = undefined;
  console.log("PASS: category/specialty CRUD and visibility controls; editable homepage settings");
  const beforeMember = await (await guestContext.request.get(`${base}/api/services`)).json();
  await member.goto(`${base}/register`, { waitUntil: "networkidle" });
  await member.screenshot({ path: ".qa/janzour-register-mobile.png", fullPage: true });
  await member.locator("[name=name]").fill(memberName); await member.locator("[name=phone]").fill("01012345678"); await member.locator("[name=username]").fill(`ui.${suffix}`);
  await member.locator("[name=password]").fill("test-pass-123"); await member.locator("[name=confirmPassword]").fill("test-pass-123");
  await member.getByRole("button", { name: "إنشاء العضوية", exact: true }).click(); await expect(member).toHaveURL(`${base}/account`);
  memberId = (await (await memberContext.request.get(`${base}/api/auth`)).json()).viewer.id;
  await expect(member.locator(".profile-member-badge")).toHaveText("عضو في الموقع");
  const afterMember = await (await guestContext.request.get(`${base}/api/services`)).json(); assert.equal(afterMember.memberCount, beforeMember.memberCount + 1); assert.equal(afterMember.services.length, beforeMember.services.length);
  await member.goto(`${base}/admin`, { waitUntil: "networkidle" }); await expect(member).toHaveURL(`${base}/account`);
  assert.equal((await memberContext.request.get(`${base}/api/admin`)).status(), 401);
  await member.goto(base, { waitUntil: "networkidle" }); await expect(member.locator('a[href="/admin"]')).toHaveCount(0);
  await admin.bringToFront(); await admin.locator(".admin-sidebar nav").getByRole("button", { name: /أعضاء الموقع/ }).click(); await admin.getByRole("button", { name: "تحديث", exact: true }).click();
  await expect(admin.locator(".admin-member-row").filter({ hasText: memberName })).toBeVisible();
  await expect(admin.locator(".member-count-banner")).toContainText(`${afterMember.memberCount} عضو مسجل`);
  await admin.screenshot({ path: ".qa/janzour-admin-members.png", fullPage: true });
  console.log("PASS: independent member signup, correct member count, member directory separation and admin denial");
  for (const width of [1440, 1024, 768, 390, 360]) {
    await page.setViewportSize({ width, height: 900 }); await page.goto(base, { waitUntil: "networkidle" });
    const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth })); assert.ok(size.content <= size.viewport, `overflow at ${width}: ${size.content}`);
    if (width === 390) { await page.screenshot({ path: ".qa/janzour-home-mobile.png", fullPage: true }); await page.getByRole("button", { name: "فتح القائمة", exact: true }).click(); await expect(page.locator(".main-nav")).toBeVisible(); await page.getByRole("button", { name: "إغلاق القائمة", exact: true }).click(); }
    console.log(`PASS: no horizontal overflow at ${width}px`);
  }
  await admin.setViewportSize({ width: 390, height: 844 }); await admin.reload({ waitUntil: "networkidle" });
  const adminSize = await admin.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth })); assert.ok(adminSize.content <= adminSize.viewport);
  await admin.screenshot({ path: ".qa/janzour-admin-mobile.png", fullPage: true });
  assert.equal(errors.length, 0, errors.join("\n")); console.log("PASS: responsive administration and no browser runtime errors");
} finally {
  await adminContext.request.post(`${base}/api/auth`, { data: { action: "login", username: "admin", password: "admin" } });
  if (savedSettings) await adminContext.request.patch(`${base}/api/admin`, { data: { type: "settings", values: savedSettings } });
  for (const [type, id] of [["service", serviceId], ["ad", adId], ["member", memberId], ["category", specialtyId], ["category", rootId]]) if (id) await adminContext.request.delete(`${base}/api/admin`, { data: { type, id } });
  await adminContext.request.delete(`${base}/api/auth`); await memberContext.request.delete(`${base}/api/auth`); await browser.close();
  console.log("Cleaned up UI test records and restored settings.");
}
